# Generated by Django 6.0.2 on 2026-05-06 13:23

import django.core.validators
import django.db.models.deletion
import shopapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, db_index=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('discount', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Discount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('preview', models.ImageField(blank=True, null=True, upload_to=shopapp.models.product_preview_directory_path, verbose_name='Preview')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name', 'price'],
                'permissions': [('can_publish_product', 'Can publish product'), ('can_archive_product', 'Can archive product'), ('can_view_archived_products', 'Can view archived products')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Delivery address')),
                ('promocode', models.CharField(blank=True, max_length=20, verbose_name='Promocode')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('receipt', models.FileField(null=True, upload_to='orders/receipts/', verbose_name='Receipt')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('products', models.ManyToManyField(related_name='orders', to='shopapp.product', verbose_name='Products')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'permissions': [('can_cancel_order', 'Can cancel order'), ('can_process_order', 'Can process order')],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shopapp.models.product_images_directory_path, verbose_name='Image')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shopapp.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
            },
        ),
    ]
